[tools]
bun = "latest"
claude = "latest"
codex = "latest"
dotnet = "latest"
gh = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
tmux = "latest"
uv = "latest"

[settings]
experimental = true

[settings.upgrade]
auto_prune = false
